from fastapi import APIRouter, HTTPException, status
from app.db.supabase import supabase
from app.schemas.party import (
    PartyCreate,
    PartyResponse,
    PartyCreatedResponse,
    PartyAdminAction,
)

router = APIRouter(prefix="/api/party", tags=["Party"])


@router.post("", response_model=PartyCreatedResponse, status_code=status.HTTP_201_CREATED)
def create_party(party: PartyCreate):
    """Create a new Secret Santa party."""
    
    # Prepare data for insertion (passcode is auto-generated by Supabase)
    party_data = {
        "id": party.id,
        "name": party.name,
        "description": party.description,
        "budget": party.budget,
        "currency": party.currency,
        "event_date": str(party.event_date),
        "event_time": str(party.event_time),
        "organizer_name": party.organizer_name,
        "organizer_email": party.organizer_email,
        "status": True,  # New parties are always OPEN
    }
    
    # Insert party
    response = supabase.table("parties").insert(party_data).execute()
    
    if not response.data:
        raise HTTPException(status_code=500, detail="Failed to create party")
    
    created_party = response.data[0]
    
    # If organizer wants to participate, add them as first participant
    if party.participate:
        participant_data = {
            "party_id": party.id,
            "name": party.organizer_name,
            "email": party.organizer_email,
        }
        supabase.table("participants").insert(participant_data).execute()
    
    return PartyCreatedResponse(
        id=created_party["id"],
        passcode=created_party["passcode"],
        name=created_party["name"],
    )


@router.get("/{party_id}", response_model=PartyResponse)
def get_party(party_id: str):
    """Get party details by ID."""
    
    response = supabase.table("parties").select("*").eq("id", party_id).execute()
    
    if not response.data:
        raise HTTPException(status_code=404, detail="Party not found")
    
    return response.data[0]


@router.delete("/{party_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_party(party_id: str, auth: PartyAdminAction):
    """Delete a party. Requires master passcode."""
    
    # Verify passcode
    party_response = supabase.table("parties").select("passcode").eq("id", party_id).execute()
    
    if not party_response.data:
        raise HTTPException(status_code=404, detail="Party not found")
    
    if party_response.data[0]["passcode"] != auth.passcode:
        raise HTTPException(status_code=403, detail="Invalid passcode")
    
    # Delete party (cascade will delete participants)
    supabase.table("parties").delete().eq("id", party_id).execute()
    
    return None


@router.post("/{party_id}/lock")
def lock_party_and_match(party_id: str, auth: PartyAdminAction):
    """Lock the party and trigger matching. Requires master passcode."""
    
    # Verify passcode and get party
    party_response = supabase.table("parties").select("*").eq("id", party_id).execute()
    
    if not party_response.data:
        raise HTTPException(status_code=404, detail="Party not found")
    
    party = party_response.data[0]
    
    if party["passcode"] != auth.passcode:
        raise HTTPException(status_code=403, detail="Invalid passcode")
    
    if not party["status"]:  # Already locked
        raise HTTPException(status_code=400, detail="Party is already locked")
    
    # Get participants
    participants_response = supabase.table("participants").select("*").eq("party_id", party_id).execute()
    participants = participants_response.data
    
    if len(participants) < 2:
        raise HTTPException(status_code=400, detail="Need at least 2 participants to start matching")
    
    # TODO: Call matching algorithm from utils/matching.py
    # TODO: Send emails via utils/email.py
    
    # Lock the party
    supabase.table("parties").update({"status": False}).eq("id", party_id).execute()
    
    return {"message": "Matching complete! Emails have been sent."}


@router.post("/{party_id}/resend")
def resend_all_emails(party_id: str, auth: PartyAdminAction):
    """Resend all match emails. Requires master passcode."""
    
    # Verify passcode and get party
    party_response = supabase.table("parties").select("*").eq("id", party_id).execute()
    
    if not party_response.data:
        raise HTTPException(status_code=404, detail="Party not found")
    
    party = party_response.data[0]
    
    if party["passcode"] != auth.passcode:
        raise HTTPException(status_code=403, detail="Invalid passcode")
    
    if party["status"]:  # Party is still open
        raise HTTPException(status_code=400, detail="Matching has not started yet.")
    
    # TODO: Resend all emails via utils/email.py
    
    return {"message": "All match emails have been resent."}

