from pydantic import BaseModel, EmailStr
from datetime import date, time
from typing import Optional


# --- Request Schemas ---

class PartyCreate(BaseModel):
    """Schema for creating a new party"""
    id: str  # The 6-char code, generated by frontend or backend
    name: str
    description: Optional[str] = ""
    budget: Optional[int] = None
    currency: str
    event_date: date
    event_time: time
    organizer_name: str
    organizer_email: EmailStr
    participate: bool = True  # Should the organizer be added as a participant?


class PartyAdminAction(BaseModel):
    """Schema for actions requiring the master passcode"""
    passcode: str


# --- Response Schemas ---

class PartyResponse(BaseModel):
    """Schema for returning party details (public view)"""
    id: str
    name: str
    description: Optional[str]
    budget: Optional[int]
    currency: str
    event_date: date
    event_time: time
    organizer_name: str
    organizer_email: EmailStr
    status: bool  # True = OPEN, False = LOCKED


class PartyCreatedResponse(BaseModel):
    """Schema returned after creating a party (includes passcode)"""
    id: str
    passcode: str  # Only shown once at creation time
    name: str

